services:
  metabase:
    image: metabase/metabase:v0.53.7
    container_name: metabase
    ports:
      - "3002:3000"
    environment:
      MB_SITE_URL: ${METABASE_SITE_URL:-http://localhost:3002}
      MB_JETTY_PORT: 3000
    restart: unless-stopped
