  version: "3.8"

  services:
    openobserve:
      image: public.ecr.aws/zinclabs/openobserve:latest
      container_name: openobserve
      ports:
        - "5080:5080"
      environment:
        ZO_ROOT_USER_EMAIL: ${ZO_ROOT_USER_EMAIL:-admin@example.com}
        ZO_ROOT_USER_PASSWORD: ${ZO_ROOT_USER_PASSWORD:-Complexpass#123}
      volumes:
        - openobserve_data:/data
      restart: unless-stopped

  volumes:
    openobserve_data: